---
controller_credential_types:
  - name: Demo App Custom
    kind: cloud
    inputs:
      fields:
        - id: username
          type: string
          label: Username
        - id: password
          type: string
          label: password
          secret: true
      required:
        - username
        - password
    injectors:
      extra_vars:
        custom_username: !unsafe "{{ username }}"
        custom_password: !unsafe "{{ password }}"
